name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build application
      run: npm run build
    
    - name: Build Docker image
      run: docker build -t polydraw:test .
    
    - name: Test Docker container
      run: |
        # Start container in background
        docker run -d --name polydraw-test -p 3001:80 polydraw:test
        
        # Wait for container to start
        sleep 10
        
        # Test basic connectivity
        for i in {1..5}; do
          if curl -f http://localhost:3001/; then
            echo "✅ Container is responding!"
            break
          fi
          echo "⏳ Attempt $i: Waiting for container..."
          sleep 5
        done
        
        # Clean up
        docker stop polydraw-test
        docker rm polydraw-test
